FROM python:3.8-alpine

WORKDIR /app

COPY ./requirements-test.txt ./

RUN apk add --no-cache --virtual .pynacl_deps build-base gcc make python3 python3-dev libffi-dev \
    && pip3 install --upgrade setuptools pip \
    && pip3 install --no-cache-dir -r requirements-test.txt \
    && rm requirements-test.txt

COPY ./utils/*.py ./utils/
COPY ./*.py ./

ENV LOCALSTACK_HOST localstack

ENTRYPOINT ["pytest", "-s", "-v"]