version: '3.2'
services:
  localstack:
    image: localstack/localstack:0.10.6
    container_name: localstack-pytesting
    ports:
      - '4563-4599:4563-4599'
#      - '8080:8080'
    environment:
      - SERVICES=s3,sqs
    logging:
      driver: "none"
  cloud-job-tests:
    container_name: cloud-job-tests
    build:
      context: .
      dockerfile: Dockerfile-tests
    depends_on:
      - "localstack"
